name: "\U0001F41E 错误反馈"
title: '[bug] '
description: 创建报告以帮助我们改进
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写此错误报告！
  - type: textarea
    id: bug-description
    attributes:
      label: 描述错误
      description: 一个关于错误的清晰简洁的描述
      placeholder: 我在做... 我所期望的是... 实际发生的是...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: 在帮助菜单栏中找到`关于`选项, 然后复制版本号
      placeholder: v0.8
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 重现步骤
      description: 请提供可能需要描述的任何复制步骤
  - type: textarea
    id: additional-info
    attributes:
      label: 附加信息
      description: 如果有必要, 在帮助菜单栏中找到`打开日志文件夹`选项并上传日志文件

